on:
  workflow_call:
    inputs:
      repostitory:
        description: 'Name of source repository'
        default: ${{ github.repository }}
        required: true
        type: string
    version:
      repostitory:
        description: 'Name of version'
        required: true
        type: string
    secrets:
      TOKEN:
        required: true

jobs:
  publish-vpm:
    runs-on: ubuntu-latest
    if: inputs.publish
    needs: create-release
    environment:
      name: vpm.anatawa12.com
      url: https://vpm.anatawa12.com/
    steps:
      - name: Prepare Dispatch payload
        env:
          REPO: ${{ inputs.repository }}
          VERSION: ${{ inputs.version }}
        run: |
          PAYLOAD="$(echo "{}" | jq -c \
            --arg REPO "$REPO" \
            --arg VERSION "$VERSION" \
            '.repository=$REPO | .version=$VERSION')"

          echo "PAYLOAD=$PAYLOAD" >> "$GITHUB_ENV"

      - name: Dispatch vpm repo update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: anatawa12/vpm.anatawa12.com
          event-type: update-package
          client-payload: ${{ env.PAYLOAD }}
