on:
  workflow_dispatch: {}
  # disable for now
  #schedule:
  #  - cron:  '0 * * * *'

jobs:
  publish-vpm:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          ref: curated
      - uses: snow-actions/git-config-user@v1.0.0

      - name: update curated repo
        run: cd curated && ./update.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
