on:
  repository_dispatch:
    types: [update-package]
  workflow_dispatch:
    inputs:
      repostitory:
        description: 'Name of source repository'
        required: true
        type: string
      version:
        description: 'Name of version'
        type: string
      website_zip:
        description: 'URL to zip file for website'
        required: false
        type: string
      website_path:
        description: 'the path to zip will be extracted to'
        required: false
        type: string
  workflow_call:
    inputs:
      repostitory:
        description: 'Name of source repository'
        default: ${{ github.repository }}
        type: string
      version:
        description: 'Name of version'
        required: true
        type: string
      environment:
        description: 'Name of environment you may use'
        required: false
        type: string
      website_zip:
        description: 'URL to zip file for website'
        required: false
        type: string
      website_path:
        description: 'the path to zip will be extracted to'
        required: false
        type: string
    secrets:
      TOKEN:
        required: true

jobs:
  publish-vpm:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      SRC_REPO: ${{ inputs.repostitory || github.event.client_payload.repository }}
      VERSION: ${{ inputs.version || github.event.client_payload.version }}
      WEBSITE_ZIP: ${{ inputs.website_zip }}
      WEBSITE_PATH: ${{ inputs.website_path }}
    environment:
      name: ${{ inputs.environment }}
      url: https://vpm.anatawa12.com/vpm.json
    steps:
      - uses: actions/checkout@v3
        with:
          repository: anatawa12/vpm.anatawa12.com
          token: ${{ secrets.TOKEN || github.token }}
          ref: master
      - uses: snow-actions/git-config-user@v1.0.0
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Perform Update Process
        run: deno run --allow-net --allow-write --allow-run update-script/update-package.ts
